#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Generate order form

from os import environ

print('''.. raw:: html

  <form method="POST" action="%s/process-order.cgi">
    <input type="text" name="first_name" />
    <input type="submit" name="Order" />
  </form>

''') % environ['PAGEGEN_BASE_URL']
