
			<!-- Footer -->
				<div id="footer-wrapper">
					<section id="footer" class="container">
						<div class="row">
							<div class="4u 12u(mobile)">
								<section>
									<header>
										<h2>Snarveier</h2>
									</header>
									<ul class="divided">
										<li><a href="{{base_url}}/microgreens">Produkter</a></li>
										<li><a href="{{base_url}}/bestilling">Bestilling</a></li>
										<li><a href="{{base_url}}/om-oss">Om South Coast Farms</a></li>
									</ul>
								</section>
							</div>
							<div class="4u 12u(mobile)">
								<section>
									<header>
										<h2>Kontakt</h2>
									</header>
									<ul class="contact">
										<li>
											<h3>Epost</h3>
											<p><a href="mailto:post@southcoastfarms.no">post@southcoastfarms.no</a></p>
										</li>
										<li>
											<h3>Telefon</h3>
											<p>(+47) 472 24 390</p>
										</li>
										<li>
											<h3>Adresse</h3>
											<p>
												Barbudalen 39<br />4846 Arendal
											</p>
										</li>
										<li>
											<h3>Organisasjon</h3>
											<p>South Coast Farms AS, 917 425 051</p>
										</li>
									</ul>
								</section>
							</div>
							<div class="4u 12u(mobile)">
								<section>
									<header>
										<h2>Sosialt</h2>
									</header>
									<ul class="social">
										<li><a href="https://www.facebook.com/SouthCoastFarmsMicrogreens/"><img src="{{base_url}}/include/images/fb.png" alt="Facebook" /></a></li>
									</ul>
								</section>
							</div>
						</div>
						<div class="row">
							<div class="12u">

								<!-- Copyright -->
									<div id="copyright">
										<ul class="links">
											<li>&copy; South Coast Farms AS. All rights reserved.</li>
										</ul>
									</div>

							</div>
						</div>
					</section>
				</div>

		<!-- Scripts -->
			<script src="{{base_url}}/include/js/jquery.min.js"></script>
			<script src="{{base_url}}/include/js/jquery.dropotron.min.js"></script>
			<script src="{{base_url}}/include/js/skel.min.js"></script>
			<script src="{{base_url}}/include/js/skel-viewport.min.js"></script>
			<script src="{{base_url}}/include/js/util.js"></script>
			<!--[if lte IE 8]><script src="{{base_url}}/include/js/ie/respond.min.js"></script><![endif]-->
			<script src="{{base_url}}/include/js/main.js"></script>
			<script src="{{base_url}}/include/js/simpleCart_SCF.js"></script>

	</body>
</html>

