
			<!-- Footer -->
				<div id="footer-wrapper">
					<section id="footer" class="container">
						<div class="row">
							<div class="4u 12u(mobile)">
								<section>
									<header>
										<h2>Snarveier</h2>
									</header>
									<ul class="divided">
										<li><a href="{{base_url}}/bestilling">Bestilling</a></li>
										<li><a href="{{base_url}}/microgreens">Microgreens</a></li>
										<li><a href="{{base_url}}/om-oss">Om South Coast Farms</a></li>
										<li><a href="https://www.facebook.com/SouthCoastFarmsMicrogreens/"><img src="{{base_url}}/include/images/fb.png" alt="Facebook" /></a></li>
									</ul>
								</section>
							</div>
							<div class="4u 12u(mobile)">
								<section>
									<header>
										<h2>Kontakt</h2>
									</header>
									<ul class="contact">
										<li>
											<h3>Epost</h3>
											<p><a href="mailto:post@southcoastfarms.no">post@southcoastfarms.no</a></p>
										</li>
										<li>
											<h3>Telefon</h3>
											<p>(+47) 472 24 390</p>
										</li>
										<li>
											<h3>Adresse</h3>
											<p>
												Barbudalen 39<br />4846 Arendal
											</p>
										</li>
										<li>
											<h3>Organisasjon</h3>
											<p>South Coast Farms AS, 917 425 051</p>
										</li>
									</ul>
								</section>
							</div>
							<div class="4u 12u(mobile)">
								<section>
									<header>
										<h2>Motta ukentlig fresh sheet</h2>
									</header>

									<p>Fresh sheetet er liste av microgreens vi har tilgjenglig for levering samme uka.</p>

<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="//southcoastfarms.us15.list-manage.com/subscribe/post?u=3457ecd1e835fd6175a78c51a&amp;id=c7110c67ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
<div class="mc-field-group">
	<label for="mce-EMAIL">E-post  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Fornavn </label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Etternavn </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_3457ecd1e835fd6175a78c51a_c7110c67ef" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Meld meg på" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->


								</section>
							</div>
						</div>
						<div class="row">
							<div class="12u">

								<!-- Copyright -->
									<div id="copyright">
										<ul class="links">
											<li>&copy; South Coast Farms AS. All rights reserved.</li>
										</ul>
									</div>

							</div>
						</div>
					</section>
				</div>

		<!-- Scripts -->
			<script src="{{base_url}}/include/js/jquery.min.js"></script>
			<script src="{{base_url}}/include/js/jquery.dropotron.min.js"></script>
			<script src="{{base_url}}/include/js/skel.min.js"></script>
			<script src="{{base_url}}/include/js/skel-viewport.min.js"></script>
			<script src="{{base_url}}/include/js/util.js"></script>
			<!--[if lte IE 8]><script src="{{base_url}}/include/js/ie/respond.min.js"></script><![endif]-->
			<script src="{{base_url}}/include/js/main.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97434434-1', 'auto');
  ga('send', 'pageview');
</script>
	</body>
</html>

