<!DOCTYPE HTML>
<!-- Design Dopetrope by HTML5 UP -->
<html>
	<head>
		<meta charset="utf-8" />
		<base href="{{base_url}}" />
		<title>{{title}} - South Coast Farms</title>
		<meta name="description" content="{{description}}"/>
		<base href="{{base_url}}" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{{base_url}}/include/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{{base_url}}/include/css/main.css" />
		<link rel="stylesheet" href="{{base_url}}/include/css/jquery-ui.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{{base_url}}/include/css/ie8.css" /><![endif]-->
		<link rel="apple-touch-icon" sizes="57x57" href="{{base_url}}/include/icons/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="{{base_url}}/include/icons/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="{{base_url}}/include/icons/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="{{base_url}}/include/icons/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="{{base_url}}/include/icons/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="{{base_url}}/include/icons/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="{{base_url}}/include/icons/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="{{base_url}}/include/icons/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="{{base_url}}/include/icons/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="{{base_url}}/include/icons/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="{{base_url}}/include/icons/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="{{base_url}}/include/icons/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="{{base_url}}/include/icons/favicon-16x16.png">
		<link rel="manifest" href="{{base_url}}/include/icons/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="{{base_url}}/include/icons/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">
		<script type = "text/javascript" src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script type="text/javascript" src="{{base_url}}/include/js/jquery-ui.js"></script>
		<script type="text/javascript" src="{{base_url}}/include/js/jquery.ui.datepicker-nb.js"></script>
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header-wrapper">
					<div id="header">

						<!-- Logo -->
							<h1><a href="{{base_url}}/"><img src="{{base_url}}/include/images/south-coast-farms-logo.svg" width="500"  alt="South Coast Farms - Microgreens" onerror="this.src='{{base_url}}/include/images/south-coast-farms-logo.png'" /></a></h1>

						<!-- Nav -->
							<nav id="nav">{{menu}}</nav>
